global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.75:9000']


  - job_name: 'booking_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.2.75:8111']
        labels:
          application: 'Booking Service Application'

  - job_name: 'flight_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.2.75:8182']
        labels:
          application: 'Flight Service Application'

  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.2.75:8183']
        labels:
          application: 'Notification Service Application'

  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.2.75:8184']
        labels:
          application: 'User Service Application'
  - job_name: 'dicovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.2.75:8761']
        labels:
          application: 'dicovery Service Application'
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.2.75:8181']
        labels:
          application: 'api-gateway Service Application'
  - job_name: 'axonserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.2.75:8024']
        labels:
          application: 'axon server Service Application'
